# Step 1: Build stage
FROM node:20 AS build-stage
WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .

# Pass backend URL at build time
ARG REACT_APP_API_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL

RUN npm run build

# Step 2: Runtime stage
FROM tomcat:9-jdk17
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy build into Tomcat ROOT
COPY --from=build-stage /app/dist /usr/local/tomcat/webapps/ROOT

EXPOSE 8080
CMD ["catalina.sh", "run"]
